version: '3.9'

services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: 'dimipay_pt'
    ports:
      - '3307:3306'
    volumes:
      - mysql_db:/var/lib/mysql

  api:
    build: .
    ports:
      - 5001:5000
    depends_on:
      - mysql
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      IMAGEBB_API: ${IMAGEBB_API}
      NODE_ENV: production
      NODE_PATH: dist

volumes:
  mysql_db:
